{
 "title": "Bind DNS",
 "description": "Bind DNS Service Statistics.\r\n",
 "tags": [
  "dns",
  "bind",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(bind_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Node information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Restarted",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(bind_boot_time_seconds{instance=~\"$node:.*\"})"
    }
   ]
  },
  {
   "title": "Reconfigured",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(bind_config_time_seconds{instance=~\"$node:.*\"})"
    }
   ]
  },
  {
   "title": "Named CPU Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(bind_process_cpu_seconds_total{instance=~\"$node:.*\"}[120s])"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=~\"$node:.*\",mode!=\"idle\"}[5m]))"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:.*\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$node:.*\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$node:.*\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node:.*\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node:.*\"})"
    }
   ]
  },
  {
   "title": "Internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bind_process_max_fds{instance=~\"$node:.*\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "bind_process_open_fds{instance=~\"$node:.*\"}",
       "legendFormat": "Open"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "bind_process_virtual_memory_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Virtual"
      },
      {
       "expr": "bind_process_resident_memory_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Resident"
      }
     ]
    }
   ]
  },
  { "title": "Requests and responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Incoming Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_incoming_queries_total{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Incoming Request Opcodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_incoming_requests_total{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "{{ opcode }}"
    }
   ]
  },
  {
   "title": "Response Results",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_responses_total{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  { "title": "Failed queries and recursion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_query_duplicates_total{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "Duplicates"
    },
    {
     "expr": "rate(bind_query_errors_total{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "{{ error }}"
    },
    {
     "expr": "rate(bind_query_recursions_total{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "Recursions"
    }
   ]
  },
  { "title": "Resolver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Resolver Cache RR Sets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bind_cache_rrsets{instance=~\"$node:.*\"}",
     "legendFormat": "{{ view }} / {{ type }}"
    }
   ]
  },
  {
   "title": "DNSSEC Validation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_dnssec_validation_errors_total{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "{{ view }} / ValErr"
    },
    {
     "expr": "increase(bind_resolver_dnssec_validation_success_total{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "{{ view }} / {{ result }}"
    }
   ]
  },
  {
   "title": "Resolver Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_incoming_queries_total{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "{{ view }} / {{ type }}"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_query_errors_total{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "{{ view }} / {{ error }}"
    },
    {
     "expr": "increase(bind_resolver_query_edns0_errors_total{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "{{ view }} / EDNS0"
    },
    {
     "expr": "increase(bind_resolver_query_retries_total{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "{{ view }} / Retry"
    }
   ]
  },
  {
   "title": "Query By Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_query_duration_seconds_bucket{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "{{ view }} / {{ le }}"
    }
   ]
  },
  {
   "title": "Resolver Response Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bind_resolver_response_errors_total{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "{{ view }} / {{ error }}"
    },
    {
     "expr": "increase(bind_resolver_response_lame_total{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "{{ view }} / LAME"
    },
    {
     "expr": "increase(bind_resolver_response_mismatch_total{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "{{ view }} / MISMATCH"
    },
    {
     "expr": "increase(bind_resolver_response_truncated_total{instance=~\"$node:.*\"}[120s])",
     "legendFormat": "{{ view }} / TRUNCATED"
    }
   ]
  }
 ]
}