{
 "title": "Cache health",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "alias",
    "query": "label_values(nginx_http_request_cache_total, alias)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request rate on $alias",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "repeat": "alias",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_request_total{alias=~\"$alias.*\"}[5m])",
     "legendFormat": "Accesses"
    }
   ]
  },
  {
   "title": "Hit ratio on $alias",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "repeat": "alias",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nginx_http_request_cache_total{alias=~\"$alias\"}",
     "legendFormat": "{{upstream_cache_status}}"
    }
   ]
  },
  {
   "title": "Request latency (hits)  on $alias",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "repeat": "alias",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_http_request_time_seconds_bucket{upstream_cache_status=\"HIT\",alias=~\"^$alias.*\"}[5m])) by (vhost,le))",
     "legendFormat": "{{vhost}}/50pct"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(nginx_http_request_time_seconds_bucket{upstream_cache_status=\"HIT\",alias=~\"^$alias.*\"}[5m])) by (vhost,le))",
     "legendFormat": "{{vhost}}/90pct"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_http_request_time_seconds_bucket{upstream_cache_status=\"HIT\",alias=~\"^$alias.*\"}[5m])) by (vhost,le))",
     "legendFormat": "{{vhost}}/99pct"
    }
   ]
  },
  {
   "title": "Request latency on $alias",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "repeat": "alias",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_http_request_time_seconds_bucket{alias=~\"^$alias.*\"}[5m])) by (vhost,le))",
     "legendFormat": "{{vhost}}/50pct"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(nginx_http_request_time_seconds_bucket{alias=~\"^$alias.*\"}[5m])) by (vhost,le))",
     "legendFormat": "{{vhost}}/90pct"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_http_request_time_seconds_bucket{alias=~\"^$alias.*\"}[5m])) by (vhost,le))",
     "legendFormat": "{{vhost}}/99pct"
    }
   ]
  },
  {
   "title": "Disk Space Used on $alias",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "repeat": "alias",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_avail_bytes{alias=~\"$alias.*\",device!~'by-uuid'} / node_filesystem_size_bytes{alias=~\"$alias.*\",device!~'by-uuid'}) or 100.0 - 100 * (node_filesystem_avail{alias=~\"$alias.*\",device!~'by-uuid'} / node_filesystem_size{alias=~\"$alias.*\",device!~'by-uuid'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Traffic on $alias",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "repeat": "alias",
   "yaxes": [
    { "format": "bits", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{alias=~'$alias.*'}[5m])*8 or irate(node_network_receive_bytes{alias=~'$alias.*'}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=~'$alias.*'}[5m])*8 or irate(node_network_transmit_bytes{alias=~'$alias.*'}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "Load on $alias",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "repeat": "alias",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=~\"$alias.*\"}",
     "legendFormat": "load"
    },
    {
     "expr": "node_load5{alias=~\"$alias.*\"}",
     "legendFormat": "load"
    },
    {
     "expr": "node_load15{alias=~\"$alias.*\"}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Memory on $alias",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "repeat": "alias",
   "yaxes": [
    { "format": "bytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{alias=~'$alias.*'} - node_memory_MemFree_bytes{alias=~'$alias.*'} - node_memory_Buffers_bytes{alias=~'$alias.*'} - node_memory_Cached_bytes{alias=~'$alias.*'} - node_memory_SwapCached_bytes{alias=~'$alias.*'} - node_memory_Slab_bytes{alias=~'$alias.*'} - node_memory_PageTables_bytes{alias=~'$alias.*'} - node_memory_VmallocUsed_bytes{alias=~'$alias.*'} ) or ( node_memory_MemTotal{alias=~'$alias.*'} - node_memory_MemFree{alias=~'$alias.*'} - node_memory_Buffers{alias=~'$alias.*'} - node_memory_Cached{alias=~'$alias.*'} - node_memory_SwapCached{alias=~'$alias.*'} - node_memory_Slab{alias=~'$alias.*'} - node_memory_PageTables{alias=~'$alias.*'} - node_memory_VmallocUsed{alias=~'$alias.*'} )",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{alias=~'$alias.*'} or node_memory_Buffers{alias=~'$alias.*'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{alias=~'$alias.*'} or node_memory_Cached{alias=~'$alias.*'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{alias=~'$alias.*'} or node_memory_MemFree{alias=~'$alias.*'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Slab_bytes{alias=~'$alias.*'} or node_memory_Slab{alias=~'$alias.*'}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_SwapCached_bytes{alias=~'$alias.*'} or node_memory_SwapCached{alias=~'$alias.*'}",
     "legendFormat": "SwapCached"
    },
    {
     "expr": "node_memory_PageTables_bytes{alias=~'$alias.*'} or node_memory_PageTables{alias=~'$alias.*'}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{alias=~'$alias.*'} or node_memory_VmallocUsed{alias=~'$alias.*'}",
     "legendFormat": "VmallocUsed"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{alias=~'$alias.*'} - node_memory_SwapFree{alias=~'$alias.*'}) or (node_memory_SwapTotal{alias=~'$alias.*'} - node_memory_SwapFree{alias=~'$alias.*'})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_Committed_AS_bytes{alias=~'$alias.*'} or node_memory_Committed_AS{alias=~'$alias.*'}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_Mapped_bytes{alias=~'$alias.*'} or node_memory_Mapped{alias=~'$alias.*'}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_Active_bytes{alias=~'$alias.*'} or node_memory_Active{alias=~'$alias.*'}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Inactive_bytes{alias=~'$alias.*'} or node_memory_Inactive{alias=~'$alias.*'}",
     "legendFormat": "Inactive"
    }
   ]
  }
 ]
}