{
 "title": "TPO overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Home Dashboard</span>\n</div>\n\n<div class=\"text-center\">\nThis dashboard provides an overview of all the systems monitored by Grafana and Prometheus. Head to the left menu for more dashboards or the top-left of this dashboard.\n</div>\n\n<div class=\"text-center\" style=\"font-size: smaller\">\nPossible additions, the number of:\n\n<ul>\n<li>sysadmins?</li>\n<li>users?</li>\n<li>CPU cores?</li>\n<li>open tickets?</li>\n<li>closed ticket in the last month?</li>\n<li>tickets processed per sysadmin?</li>\n<li>SLA metrics fulfilled?</li>\n<li>backup disk usage?</li>\n<li>overall disk usage?</li>\n<li>nagios green?</li>\n<li>metrics counts?</li>\n</ul>\n</div>"
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(node_load1)", "legendFormat": "1-minute load" },
    { "expr": "avg(node_load5)", "legendFormat": "5-minute load" },
    { "expr": "avg(node_load15)", "legendFormat": "15-minute load" }
   ]
  },
  {
   "title": "Unreachable hosts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(up!=1)" }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
   "targets": [
    { "expr": "avg(node_load15)" }
   ]
  },
  {
   "title": "Apache hit rate",
   "type": "singlestat",
   "description": "Average Apache hit rate over the last 30 days",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 5 },
   "format": "reqps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(apache_accesses_total[30d]))",
     "legendFormat": "WTH"
    }
   ]
  },
  {
   "title": "Pending reboots",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(node_reboot_required)" }
   ]
  },
  {
   "title": "Pending upgrades",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(apt_upgrades_pending)" }
   ]
  },
  {
   "title": "Apache hit rate",
   "type": "graph",
   "description": "Average Apache hit rate over the last 30 days",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apache_accesses_total[5m]))",
     "legendFormat": "Apache hit rate"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "description": "Total memory use. Note that this counts virtual machines in double.",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Total  memory"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"}) + count(node_cpu{mode=\"system\"})",
     "legendFormat": "Number of cores"
    }
   ]
  },
  {
   "title": "Host count",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 13 },
   "targets": [
    { "expr": "count(up) by (job)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "table",
   "description": "Total memory use. Note that this counts virtual machines in double.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
   "targets": [
    { "expr": "sum(node_memory_MemFree_bytes)", "legendFormat": "Free memory" },
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Total  memory"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[5m]))",
     "legendFormat": "Transmit rate"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m]))",
     "legendFormat": "Receive rate"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[5m]))",
     "legendFormat": "Transmit rate"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m]))",
     "legendFormat": "Receive rate"
    }
   ]
  },
  {
   "title": "Pending reboots",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(node_reboot_required)", "legendFormat": "hosts requiring a reboot" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "description": "Total memory use. Note that this counts virtual machines in double.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sum(node_memory_MemFree_bytes)", "legendFormat": "Free memory" },
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Total  memory"
    }
   ]
  },
  {
   "title": "Pending upgrades",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apt_upgrades_pending)",
     "legendFormat": "Total number of packages needing upgrading"
    },
    { "expr": "count(apt_upgrades_pending>0)", "legendFormat": "Hosts requiring upgrades" }
   ]
  },
  {
   "title": "Host count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(up) by (job)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Unreachable hosts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(up!=1) by (job)", "legendFormat": "{{job}}" }
   ]
  }
 ]
}